In [3]:
import pandas as pd
from datetime import date, datetime
from scipy.stats import pearsonr
import numpy as np

In [4]:
# Load some comments
df = pd.read_parquet("bitcoin.parquet")
df['dt'] = pd.to_datetime(df.dt, unit='ms')
df.rename(columns={'parent_id': 'id'}, inplace=True)
df.head()

,body,id,dt,score
0,You arent really getting the point if you just...,c1hqgwf,2011-02-22 06:09:20,10
1,The point is that it enables people like you a...,c1hqgwf,2011-02-22 06:36:33,15
2,The deflationary spiral is a myth.\n\nPrices g...,fv4xn,2011-03-01 16:52:21,17
3,Empirical evidence shows that it is false that...,c1iuhaw,2011-03-01 18:33:44,14
4,from #bitcoin-dev @irc.freenode.net this morni...,c1jorx4,2011-03-07 14:11:57,12

In [4]:
# Load some articles
df = pd.read_parquet("output.parquet")
df.head()
df['dt'] = pd.to_datetime(df.dt, unit='ms')
df.head()

,title,description,body,url,domain,dt
0,Will glucose monitors become the next wellness...,"A new device from Abbott Laboratories, called ...","In recent years, smartwatches and smart rings ...",https://www.mercurynews.com/2024/10/30/will-gl...,The Mercury News,2024-10-30 20:06:16
1,Will glucose monitors become the next wellness...,"A new device from Abbott Laboratories, called ...","In recent years, smartwatches and smart rings ...",https://www.chicagotribune.com/2024/10/22/will...,Chicago Tribune,2024-10-22 10:00:39
2,"Taiwan Semi, Netflix, Goldman Sachs, Citi earn...","Charles Schwab, Bank of America, Johnson & Joh...","As earnings season takes off, CNBC's Jim Crame...",https://www.cnbc.com/2024/10/11/cramers-week-a...,CNBC,2024-10-11 22:42:27
3,Abbott launches its first over-the-counter con...,"Abbott Laboratories announced Lingo, its first...",Abbott Laboratories announced Thursday its ove...,https://www.cnbc.com/2024/09/05/-abbott-launch...,CNBC,2024-09-05 13:00:01
4,Abbott Labs falls after jury awards plaintiff ...,Abbott Laboratories stock dropped 3% in after-...,"Update 8:10pm: Updates damage amount, adds Abb...",https://seekingalpha.com/news/4129212-abbott-l...,Seeking Alpha,2024-07-27 00:07:00